name: build

on:
  push:
    # enable next line to limit branches to run
    branches: [ "master" ]
  pull_request:
    # enable next line to limit branches to run
    # branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

#    not needed currently, but leaving here for future use
#    - uses: actions/setup-python@v4
#      with:
#        python-version: '2.7.18'     

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
    - name: Package
      run: |    
        npm run dist
